# Generated by Django 4.0.6 on 2022-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Genre')),
                ('discriptione', models.TextField(blank=True, verbose_name='Genre discriptione')),
            ],
        ),
    ]
