# Generated by Django 4.0.6 on 2022-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Series title')),
                ('discription', models.TextField(blank=True, verbose_name='Series discription')),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='discriptione',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='discriptione',
        ),
        migrations.AddField(
            model_name='genre',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Genre discription'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Publisher discription'),
        ),
    ]
