# Generated by Django 4.0.6 on 2022-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_genre_options_alter_publisher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Author's name")),
                ('surname', models.CharField(max_length=50, verbose_name="Author's surname")),
                ('biography', models.TextField(default="Fill in the author's biography", verbose_name="Author's biography")),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.AlterField(
            model_name='genre',
            name='discription',
            field=models.TextField(default="Fill in the genre's discription", verbose_name='Genre discription'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='discription',
            field=models.TextField(default="Fill in the publisher's discription", verbose_name='Publisher discription'),
        ),
        migrations.AlterField(
            model_name='series',
            name='discription',
            field=models.TextField(default='Fill series discription', verbose_name='Series discription'),
        ),
    ]
