# Generated by Django 4.0.6 on 2022-07-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_author_alter_genre_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Book title')),
                ('photo', models.ImageField(upload_to='', verbose_name='Cover photo')),
                ('price', models.PositiveIntegerField(verbose_name='Book price')),
                ('year_of_publication', models.PositiveIntegerField(verbose_name='Year of publication')),
                ('pages', models.PositiveIntegerField(verbose_name='Pages')),
                ('binding', models.CharField(max_length=50, verbose_name='Book binding')),
                ('book_format', models.CharField(max_length=50, verbose_name='Book format')),
                ('isbn', models.PositiveIntegerField(verbose_name='ISBN')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('age_restrictions', models.PositiveIntegerField(verbose_name='Age restrictions')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('activity', models.BooleanField(default=True, verbose_name='Activity')),
                ('rating', models.PositiveIntegerField(default='Select a rating from 0 to 10', verbose_name='Rating')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Date update')),
                ('authors', models.ManyToManyField(related_name='Books', to='bookstore.author', verbose_name='Authors')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.genre')),
                ('publishers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.publisher', verbose_name='Publishers')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.series')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
