# Generated by Django 4.0.6 on 2022-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date update'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='Books', to='bookstore.genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(help_text='Select a rating from 0 to 10', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight (grams)'),
        ),
    ]
